imports:
    - https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.Bombardier/bombardier.yml

jobs:
  server:
    source:
      repository: https://github.com/KriszW/kreta-fileservice-parameterhandler.git
      branchOrCommit: main
      project: src/TestUI/TestUI.csproj

scenarios:
  preview:
    application:
      job: server
    load:
      job: bombardier
      variables:
        serverPort: 5000
        path: /api/Test?type=preview
  normal:
    application:
      job: server
    load:
      job: bombardier
      variables:
        serverPort: 5000
        path: /api/Test?type=normal

profiles:
  local:
    variables:
      serverAddress: localhost
    jobs: 
      application:
        endpoints: 
          - http://localhost:5000
      load:
        endpoints: 
          - http://localhost:5000